name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    tests: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
        - name: Install dependencies
          run: | 
            python -m pip install --upgrade pip
            pip install poetry
            poetry config virtualenvs.in-project true
            poetry shell
            poetry install
        - name: Run tests
          run: |
            poetry run python -m pytest ./tests
